### ISSUE TITLE
Code Climate maintainability badge is broken

### ISSUE THREAD

**Issue by vbrazo** [akabiru/faker-bot#66]

**Comment by akabiru** [comment]
Good eye seems to be related to rubocop. Can probably be fixed by specifying a rubocop channel. 👁 

https://codeclimate.com/github/faker-ruby/faker-bot/builds/84

![Screenshot 2019-11-04 at 22 40 29](https://user-images.githubusercontent.com/17295175/68152161-25eaee80-ff54-11e9-8a5d-e314b959f63b.jpg)
